services:
  - type: web
    name: url-shortener-backend
    env: node
    buildCommand: cd BACKEND && npm install
    startCommand: cd BACKEND && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-app.onrender.com
      - key: PORT
        value: 10000

  - type: web
    name: url-shortener-frontend
    env: static
    buildCommand: cd FRONTEND && npm install && npm run build
    staticPublishPath: ./FRONTEND/dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-app.onrender.com